### ISSUE TITLE
Segmentation fault while generating training data

### ISSUE THREAD

**Issue by gplynch619** [AarhusCosmology/connect_public#4]
Hello,

I have been trying to get connect up and running, but am stuck at the stage of generating training data. After cloning the repo and setting it up according to the README, configuring my input file, and running the code I get the following error trace:

```
Traceback (most recent call last):
  File "/Users/gabe/projects/connect/connect.py", line 79, in <module>
    s.create_iterative_data()
  File "/Users/gabe/projects/connect/source/data_sampling.py", line 129, in create_iterative_data
    model = self.train_neural_network(sampling='lhc')
  File "/Users/gabe/projects/connect/source/data_sampling.py", line 63, in train_neural_network
    CSDF = CreateSingleDataFile(self.param, self.CONNECT_PATH)
  File "/Users/gabe/projects/connect/source/join_output.py", line 29, in __init__
    self.Cl_len = max(set(counts), key = counts.count) + 1
ValueError: max() arg is an empty sequence
```

It turns out that the `counts` object in `join_output.py` is empty, which is in turn because my `Cl_tt_data_x.txt` files are empty. The call that is supposed to fill these occurs in `call_calc_model.py`, and it turns out that this function leads to a segmentation fault which does not crash the program, but does exit out of the sp.Popen call early without actually filling those data files. My output.log is 

```

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 66264 RUNNING AT campus-018-240.ucdavis.edu
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault: 11 (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
No initial model given
Calculating 10000 initial CLASS models
Training neural network

```

I believe I have tracked this segmentation fault to an error occurring in the MPI communication in `calc_models_mpi.py`, specifically in the `comm.send(data[data_idx], dest=r)` statement occurring in the master rank near line 118 and the corresponding `model = comm.recv(source=0)` in the other ranks near line 191. The reason I think this is that I can insert a `comm.Barrier()` after the `else` statement near line 134 and this prevents the seg fault (although now the code hangs because the non-master ranks never get to their comm.recv statement, and rank 0 never catches up to the barrier I just inserted). Nonetheless, blocking the other ranks from reaching that recv statement prevents the seg fault. Beyond this, I cannot identify why this seg fault is occurring. Furthermore, running the code with one mpi rank avoids the segault, but crashes elsewhere due to the code expecting multiple ranks. Happy to help try and track this down further.

Other info:
This problem occurs both on my laptop, running OSX on Apple silicon, as well as on a computing cluster running Linux. On my laptop I have 8 logical cpus, on the cluster I was running with 128.

**Comment by AndreasNygaard** [comment]
Hello,
would you mind pasting your .param file here so I can try to repeat the error? I have come across the ValueError in `join_output.py` before, but that was due to a user error and I suspect that the reason here is different since no segmentation fault was happening at that time. Also, what version of `mpi4py` are you using?

**Comment by gplynch619** [comment]
Here is the param file I am using. It is minimally edited from the `example.param` file included with the code. The `xe_pert_type` parameter in "extra_params" is there because I am using a modified version of CLASS, although with this parameter set to `none` the behavior should be the same as "normal" class. I am using `mpi4py 3.1.3`.

```
# Parameter file for the example model

# Specify the parameters for the model, their minimum value and their maximum value (as you would in CLASS) 
#           | name              | min-value     | max-value      |
#           |-------------------|---------------|----------------|
parameters={'omega_b'        :  [ 0.014,          0.039          ],
            'omega_cdm'      :  [ 1e-11,          0.25           ],
            'H0'             :  [ 30,             120            ],
            'ln10^{10}A_s'   :  [ 1,              5              ],
            'n_s'            :  [ 0.7,            1.3            ],
            'tau_reio'       :  [ 0.01,           0.4            ]}

# Specify additional parameters
train_ratio         = 0.95			# Amount of data used for training (rest is used for testing)
val_ratio           = 0.05	      		# Amount of training data used for validation
epochs              = 100	      		# Number of cycles/epochs during training
batchsize           = 512	     		# Batchsize of data when training
activation_function = 'alsing'	    		# Activation function - as defined in TensorFlow or source/custom_functions.py
loss_function       = 'cosmic_variance'         # Loss function - as defined in TensorFlow or source/custom_functions.py
N_hidden_layers     = 6		    		# Number of hidden layers in fully-connected architecture
N_nodes		    = 512			# Number of nodes in each hidden layer
output_Cl           = ['tt', 'te', 'ee']	# Cl spectra in output
output_derived      = ['z_reio',   		# Derived parameters in output
		       'Omega_Lambda', 
		       'YHe', 
		       'A_s', 
		       'sigma8', 
		       '100*theta_s'
		       ]
extra_input         = {'k_pivot': 0.05,		# Extra input to CLASS
		       'N_ur':    2.0328,
		       'N_ncdm':  1,
		       'm_ncdm':  0.06,
		       'T_ncdm':  0.71611,
			   'xe_pert_type': 'none',
		       #'sBBN file': '/path/to/sBBN.dat'
		       }


# Sampling of training data can be done with the methods 'lhc' and 'iterative'. Some parameters are only usable wth the iterative method
sampling = 'iterative'
#initial_model = 'name_of_initial_model'            # Name of initial model to start the iterations
montepython_path = '/Users/gabe/projects/montepython_public'    # Path to the montepython installation
mp_tol=0.01
iter_tol=0.01
N_max_lines = 2*10**4
keep_first_iteration = False

N = 10**4					    # Amount of points in lhc. When using the iterative method this number refers to only the initial lhc
jobname = 'lcdm_example'
save_name = 'example'
overwrite_model = False

```

**Comment by gplynch619** [comment]
I have made the following script which I think reproducing the essential logic of the section in question, and this script runs without error on my system. So it is possible that the issue is not actually in the MPI communication and is something else. 
```
import sys
import os
import numpy as np
from mpi4py import MPI
import time
import itertools

N=8
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
N_slaves = comm.Get_size()-1

get_slave = itertools.cycle(range(1, N_slaves+1))

if rank == 0:
    print("I am rank {}".format(rank))
    data = []
    for i in range(N):
        params = np.random.normal(size=6)
        data.append(params)
    
    sleep_short = 0.0001
    sleep_long = 0.1
    sleep_dict = {}
    for r in range(1, N_slaves+1):
        sleep_dict[str(r)] = 1
    data_idx = 0
    while len(data) > data_idx:
        r = next(get_slave)
        if comm.iprobe(r):
            useless_info = comm.recv(source=r)
            print(useless_info)
            comm.send(data[data_idx], dest=r)
            data_idx += 1
            sleep_dict[str(r)] = 1
        else:
            sleep_dict[str(r)] = 0
        
        if all(value == 0 for value in sleep_dict.values()):
            time.sleep(sleep_long)
        else:
            time.sleep(sleep_short)

    for r in range(1, N_slaves+1):
        comm.send('Done', dest=r)

else:
    print("rank {}".format(rank))
    while True:
        comm.send("I am done", dest=0)
        model = comm.recv(source=0)
        if type(model).__name__ == 'str':
            break

MPI.Finalize()
sys.exit(0)
```
